### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by tobyhodges** [tobyhodges/working-memory-test#2]
- [ ] add another set of words for the second part of the test
- [ ] add completion text
- [ ] improve the styling of the page
- [ ] make app asynchronous (amongst other things, this should make it easier to ensure that the info text etc changes when it's supposed to)
- [ ] add citation(s)
- [ ] add link to JSvsDS
- [ ] deploy on Netlify
